import 'dotenv/config';
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://156.67.27.148:3010/');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(process.env.TEST_USER_EMAIL);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill(process.env.TEST_USER_PASSWORD);
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.goto('http://156.67.27.148:3010/Projects/Campaigns');
  await page.getByRole('button', { name: 'New Campaign' }).click();
  await page.getByRole('textbox', { name: 'Campaign Title *' }).click();
  await page.getByRole('textbox', { name: 'Campaign Title *' }).fill('Simple C');
  await page.getByRole('textbox', { name: 'Campaign Title *' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Campaign Title *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Campaign Title *' }).fill('Simple Provider');
  await page.getByRole('textbox', { name: 'Campaign Description *' }).click();
  await page.getByRole('textbox', { name: 'Campaign Description *' }).fill('sample description for campaign');
  await page.locator('div').filter({ hasText: /^Campaign Title \*Campaign Description \*sample description for campaignReason \*$/ }).first().click();
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByRole('textbox', { name: 'Reason *' }).fill('sample reason');
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByRole('textbox', { name: 'Beneficiaries *' }).click();
  await page.getByRole('textbox', { name: 'Beneficiaries *' }).fill('Open for all ages');
  await page.locator('#start_date').fill('2026-08-10');
  await page.locator('#end_date').fill('2026-08-12');
  await page.locator('#start_date').fill('2026-08-10');
  await page.locator('.css-19bb58m').first().click();
  await page.getByRole('option', { name: 'Money' }).click();
  await page.locator('.css-my3gbk-control > .css-hlgwow > .css-19bb58m').click();
  await page.getByRole('option', { name: 'Dileepa_obs' }).click();
  await page.locator('select[name="currency_type"]').selectOption('AU$');
  await page.locator('select[name="currency_type"]').selectOption('LKR');
  await page.getByRole('textbox', { name: 'Enter target amount' }).click();
  await page.getByRole('textbox', { name: 'Enter target amount' }).fill('500');
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).fill('7741258963');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('dileepabreadtech.12+plo@gmail.com');
  await page.getByRole('button', { name: 'Save' }).click();
});
